### ISSUE TITLE
First Project

### ISSUE THREAD

**Issue by nkabbara** [ilcardella/ArduinoCoffeeMachine#34]
Wow! Thanks for such a great tutorial. I'm planning to do the same for my Gaggia Classic Pro. 

Question, I don't have much experience with arduino and electronics. I'm a software guy. This feels like too big of a project to start with. 

What's in your opinion some other smaller projects (could be unrelated) to do in order to build some experience before jumping into this?

**Comment by ilcardella** [comment]
Hi, thanks for the feedback. I think if you want to start experimenting with electronics and Arduino the easiest would be to start from their official website documentation. https://www.arduino.cc/
They have a lot of tutorials and projects ideas from basics to more advanced. This will give you some basics on electronics and how thing works. Also the forum contains a lot of useful discussions.My advice is to choose a project around something you are passionate about so that it would motivate you in finishing it. For example, you like gardening then there are several project around monitoring plants, automating watering etc. If you like robotics you can find dozens of kits to assemble and code...
